name: master_plan
description: Master plan management
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  animated_tree_view: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get: ^4.6.6
  gap: ^3.0.1
  intl: ^0.18.1
  mysql1: ^0.20.0
  sticky_headers: ^0.3.0+2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_document: ^1.0.7

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
